### ISSUE TITLE
What Credentials are needed for this api?

### ISSUE THREAD

**Issue by Torbilicious** [AstinCHOI/NetStorageKit-Golang#2]
I am sorry if this is a stupid question, but what set of credentials is needed for using this api?

 * The luna control center login
 * A NetStorage upload account (And if this is it do i need a special username like with the ssh connection)
 * An API client for my main account (And if a general OPEN API one, or a OPEN CCU / Fast Purge API)

**Comment by AstinCHOI** [comment]
You can see your Netstorage account for enabling HTTP api and key. Your account ns id is key name and ns hostname can be seen in Netstorage group.

**Comment by Torbilicious** [comment]
I was able to get the right id and secret (I think) from the setup in [https://github.com/akamai/cli-netstorage#credentials](https://github.com/akamai/cli-netstorage#credentials).
But I am still struggeling to get the right hostname, because in my  NetStorage -> Storage Groups Detail view there is nothing like 'NetStorage HTTP API'.

Am I missing something? Or do I need to activate this somehow first?

**Comment by AstinCHOI** [comment]
Please see hostnames in netstorage group UI (...upload.akamai.com, download.akamai.com, -nsu.akamai.com)
There is hostname for ns api.

**Comment by AstinCHOI** [comment]
When you enable ns api, it takes time to propagate. You can check on ns account UI.
I have written these in my phone. I am out of office. You can ask also your akamai representative.

**Comment by Torbilicious** [comment]
I was still not able not find this entry, but just trying around with the postfixed '-nsu.akamai.com' I was able to get it work.
Thank you!
